### ISSUE TITLE
Problems downloading 3D BAG and combining tiles

### ISSUE THREAD

**Issue by lukasbeuster** [3DGI/3dbag-workshop-foss4gnl2021#1]
Hi Balázs

Slight issue here - but might be related to cjio and not the workshop (disclaimer). I'm also super new to using python so might be missing something obvious here. If there is a better way to report the issue please also let me know. 

Trying to download the 3D BAG for my area I'm running into issues - even before using my own area of interest.

When following the https://github.com/3DGI/3dbag-workshop-foss4gnl2021/blob/master/download.ipynb path and executing [8] the citymodel tiles download fine. Then I'm presented with an error code and the following steps don't execute fully (the two tiles don't combine. When I verify the no of cityobjects I'm left with 2265 - the exact number of the first tile. 

This is the error message I'm receiving at [8]

>>>Traceback (most recent call last):
  File "/opt/anaconda3/envs/foss4gnl_3dbag/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-11d9c7bbb3ca>", line 11, in <cell line: 11>
    cm.merge(cms)
  File "/opt/anaconda3/envs/foss4gnl_3dbag/lib/python3.9/site-packages/cjio/cityjson.py", line 1177, in merge
    imp_digits = math.ceil(abs(math.log(self.j["transform"]["scale"][0], 10)))
KeyError: 'transform'

It seems to be an issue with cjio (?).

I've tried verifying my installation and have run the code both in python 3.9.7 and 3.10 - I'm using PyCharm and have installed the conda environment you provided. Even though the package shows as installed I'm having problems accessing cjio via terminal and console (both outside and inside PyCharm) - example below.

>>> cjio --help
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for unary -: '_Helper'

Any ideas how to fix my installation of cjio, or how to troubleshoot other potential issues?

Thanks
Lukas

**Comment by balazsdukai** [comment]
Hi, yes it is indeed related to cjio.
With v0.7.0, cjio removes the `transform` property from the file when you load it with `cityjson.load()`.
The workaround for now is to install an earlier version of cjio, v0.6.10.
You can install it with `conda install cjio=0.6.10 -n foss4gnl_3dbag`, if your environment is called `foss4gnl_3dbag`

**Comment by balazsdukai** [comment]
I fixed the cjio version in the environment file.
